<?php
declare(strict_types=1);

namespace SetBased\Stratum\MySql\Test;

/**
 * Class for holding all constants generated by PhpStratum.
 */
class C
{
  /**
   * @setbased.stratum.constants
   *
   * PhpStratum will insert below this doc block constants.
   */
  public const int TST_ID_BUNNY    = 3;
  public const int TST_ID_CAT      = 4;
  public const int TST_ID_EGGS     = 2;
  public const int TST_ID_ELEPHANT = 5;
  public const int TST_ID_SPAM     = 1;
}
