language: php
php:
  - '7.3'
  - '7.4'

jobs:
  include:
    - env: DB=MYSQL8
      dist: xenial
    - env: DB=MARIA10_1
      dist: xenial
    - env: DB=MARIA10_2
      dist: xenial

before_install:
  - mysql --version
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"

install:
  - rm -f composer.lock
  - composer self-update
  - composer update

script:
  - ./bin/phing unit
